config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tops#index'
  get '/privacy_policy', to: 'tops#privacy_policy'
  get '/terms', to: 'tops#terms'
  get '/line_notify', to: 'tops#line_notify'
  get '/list_of_support', to: 'tops#list_of_support'

  resource :profile, only: %i[edit show update]

  resources :fraud_reports, only: %i[new create show]

  resources :scams, only: %i[index show] do
    collection do
      get 'autocomplete'
    end
  end

  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  resources :posts do
    resource :like, only: %i[create destroy]
    collection do
      get 'autocomplete'
    end
  end

  namespace :admin do
    root 'scams#index'
    resources :scams
    get 'login' => 'user_sessions#new', :as => :login
    post 'login' => 'user_sessions#create'
    delete 'logout' => 'user_sessions#destroy', :as => :logout
  end

  get 'images/ogp.png', to: 'images#ogp', as: 'images_ogp'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/scam.rb
class Scam < ApplicationRecord
  has_many :fraud_report, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :point_1, presence: true, length: { maximum: 255 }
  validates :point_2, presence: true, length: { maximum: 255 }
  validates :point_3, presence: true, length: { maximum: 255 }
  validates :scam_strategy, presence: true, length: { maximum: 1000 }

  def self.ransackable_attributes(_auth_object = nil)
    ['name']
  end
end

app/controllers/admin/scams_controller.rb
class Admin::ScamsController < Admin::BaseController
  before_action :set_scam, only: %i[show edit update destroy]

  def index
    @scams = Scam.order('name')
  end

  def show
    @scam_strategy = @scam.scam_strategy.split("\n")
  end

  def new
    @scam = Scam.new
  end

  def edit; end

  def create
    @scam = Scam.new(scam_params)

    if @scam.save
      redirect_to admin_scams_path, notice: '詐欺情報を作成しました'
    else
      flash.now[:alert] = '登録できませんでした'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @scam.update(scam_params)
      redirect_to admin_scam_path(@scam), notice: '編集に成功しました'
    else
      flash.now[:alert] = '編集に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @scam.destroy!
    redirect_to admin_scams_path, notice: '削除しました', status: :see_other
  end

  private

  def scam_params
    params.require(:scam).permit(:name, :content, :point_1, :point_2, :point_3, :scam_strategy)
  end

  def set_scam
    @scam = Scam.find(params[:id])
  end
end

app/controllers/scams_controller.rb
class ScamsController < ApplicationController
  skip_before_action :require_login, only: %i[show]
  def index
    @q = Scam.ransack(params[:q])
    @scams = @q.result(distinct: true).order('name').page(params[:page])
    @search_target = 'scam'
  end

  def show
    @scam = Scam.find(params[:id])
    @scam_strategy = @scam.scam_strategy.split("\n")
  end

  def autocomplete
    term = params[:q]
    @scams = Scam.where('name LIKE ?', "%#{term}%")
    render partial: 'scams/autocomplete', locals: { scams: @scams }
  end
end

app/views/admin/scams/_scam.html.erb
<div class="card bg-gray-50 shadow-xl m-4">
  <div class="card-body">
    <div class="overflow-x-auto m-10">
      <table class="table">
        <!-- head -->
        <thead>
          <tr>
            <th>詐欺名</th>
            <th>詐欺詳細</th>
            <th>編集</th>
            <th>削除</th>
          </tr>
        </thead>
        <tbody>
          <% @scams.each do |scam| %>
            <tr class="text-xl hover:bg-slate-300 text-slate-950 border-dashed">
              <td><%= scam.name %></td>
              <td>
                <%= link_to admin_scam_path(scam) do %>
                <i class="fa-solid fa-book-open fa-xl pl-4"></i>
                <% end %>
              </td>
              <td>
                <%= link_to edit_admin_scam_path(scam) do %>
                <i class="fa-solid fa-marker"></i>
                <% end %>
              </td>
              <td>
                <%= link_to admin_scam_path(scam), data: { turbo_method: :delete, turbo_confirm: "削除しますか？" } do %>
                <i class="fa-regular fa-trash-can"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/scams/edit.html.erb
<%= form_with model: @scam, url: admin_scam_path(@scam), local: true do |f| %>
  <div class="flex flex-col m-2">
    <%= f.label :name %>
    <%= f.text_field :name,  class: "text-slate-950 input input-bordered w-full" %>
  </div>
  <div class="flex flex-col m-2">
    <%= f.label :content %>
    <%= f.text_field :content,  class: "text-slate-950 input input-bordered w-full" %>
  </div>
  <div class="flex flex-col m-2">
    <%= f.label :point_1 %>
    <%= f.text_field :point_1,  class: "text-slate-950 input input-bordered w-full" %>
  </div>
  <div class="flex flex-col m-2">
    <%= f.label :point_2 %>
    <%= f.text_field :point_2,  class: "text-slate-950 input input-bordered w-full" %>
  </div>
  <div class="flex flex-col m-2">
    <%= f.label :point_3 %>
    <%= f.text_field :point_3,  class: "text-slate-950 input input-bordered w-full" %>
  </div>
  <div class="flex flex-col m-2">
    <%= f.label :scam_strategy %>
    <%= f.text_area :scam_strategy,  class: "text-slate-950 input input-bordered w-full h-64" %>
  </div>
  <div class="flex flex-row justify-center mt-10">
    <%= f.submit "更新する", class: "justify-items-center btn btn-warning w-64 rounded-full"%>
  </div>
<% end %>

app/views/admin/scams/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex flex-col items-center text-orange">
	<div class="text-slate-950 text-4xl m-6">
		<h1>詐欺情報一覧!</h1>
	</div>
	<div class="w-full">
		<% if @scams.present? %>
			<%= render partial: 'admin/scams/scam', locals: { scams: @scams }  %>
		<% else %>
			<div class="">
					詐欺情報がありません
			</div>
		<% end %>
	</div>
</div>

app/views/admin/scams/new.html.erb
<%= form_with model: @scam, url: admin_scams_path, local: true do |f| %>
  <div class="flex flex-col m-2">
    <%= f.label :name %>
    <%= f.text_field :name,  class: "text-slate-950 input input-bordered w-full" %>
  </div>
  <div class="flex flex-col m-2">
    <%= f.label :content %>
    <%= f.text_field :content,  class: "text-slate-950 input input-bordered w-full" %>
  </div>
  <div class="flex flex-col m-2">
    <%= f.label :point_1 %>
    <%= f.text_field :point_1,  class: "text-slate-950 input input-bordered w-full" %>
  </div>
  <div class="flex flex-col m-2">
    <%= f.label :point_2 %>
    <%= f.text_field :point_2,  class: "text-slate-950 input input-bordered w-full" %>
  </div>
  <div class="flex flex-col m-2">
    <%= f.label :point_3 %>
    <%= f.text_field :point_3,  class: "text-slate-950 input input-bordered w-full" %>
  </div>
  <div class="flex flex-col m-2">
    <%= f.label :scam_strategy %>
    <%= f.text_area :scam_strategy,  class: "text-slate-950 input input-bordered w-full h-64" %>
  </div>
  <div class="flex flex-row justify-center mt-10">
    <%= f.submit "作成する", class: "justify-items-center btn btn-warning w-64 rounded-full"%>
  </div>
<% end %>

app/views/admin/scams/show.html.erb
<div class="card bg-gray-50 shadow-xl m-4">
  <div class="card-body">
    <div class="flex flex-col text-center">
      <P class="pb-2 text-orange">詐欺名</p>
        <div class="mb-8 border-dashed border-b">
          <%= @scam.name %>
        </div>
      <P class="pb-2 text-orange">詐欺について一言で説明</p>
        <div class="mb-8 border-dashed border-b">
          <%= @scam.content %>
        </div>
      <P class="pb-2 text-orange">確認するポイント1</p>
        <div class="mb-8 border-dashed border-b">
          <%= @scam.point_1 %>
        </div>
      <P class="pb-2 text-orange">確認するポイント2</p>
        <div class="mb-8 border-dashed border-b">
          <%= @scam.point_2 %>
        </div>
      <P class="pb-2 text-orange">確認するポイント3</p>
        <div class="mb-8 border-dashed border-b">
          <%= @scam.point_3 %>
        </div>
      <p class="pb-2 text-orange">詐欺の詳細(詐欺師視点)</p>
        <div class="mb-8">
          <% @scam_strategy.each do |line| %>
            <div class="border-b py-2">
              <%= line %>
            </div>
          <% end %>
        </div>
    </div>
        <div class="flex flex-row justify-between mt-10">
				<%= link_to "戻る", admin_root_path, class: "btn  btn-success w-32 rounded-full" %>
				<div class="divider divider-horizontal">OR</div>
				<%= link_to "編集する", edit_admin_scam_path(@scam), class: "btn btn-warning w-32 rounded-full" %>
			</div>
  </div>
</div>