config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tops#index'
  get '/privacy_policy', to: 'tops#privacy_policy'
  get '/terms', to: 'tops#terms'
  get '/line_notify', to: 'tops#line_notify'
  get '/list_of_support', to: 'tops#list_of_support'

  resource :profile, only: %i[edit show update]

  resources :fraud_reports, only: %i[new create show]

  resources :scams, only: %i[index show] do
    collection do
      get 'autocomplete'
    end
  end

  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  resources :posts do
    resource :like, only: %i[create destroy]
    collection do
      get 'autocomplete'
    end
  end

  namespace :admin do
    root 'scams#index'
    resources :scams
    get 'login' => 'user_sessions#new', :as => :login
    post 'login' => 'user_sessions#create'
    delete 'logout' => 'user_sessions#destroy', :as => :logout
  end

  get 'images/ogp.png', to: 'images#ogp', as: 'images_ogp'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/views/shared/_before_login_header.html.erb
<!--ヘッダー部分-->
<div class="flex flex-row justify-between items-center bg-accent text-white w-full h-16 ">
	<div class="pl-4">
		<%= link_to t('header.title'),root_path %>
	</div>
		<div class="dropdown dropdown-end">
			<div tabindex="0" role="button" class="flex items-center py-2 px-4 text-sm btn m-1  mr-4 hover:bg-orange">
				<i class="fa-solid fa-bars fa-xl"></i>
			</div>
				<ul tabindex="0" class="dropdown-content menu bg-blue-100 text-slate-950 rounded-box z-[1] w-52 p-2 shadow">
					<li>
						<%= link_to new_user_path, class: "flex items-center gap-x-2 py-2 hover:bg-gray-300" do %>
							<i class="fa-solid fa-id-card fa-xl"></i>
							<%= t('header.users') %>
						<% end %>
					</li>
					<li>
						<%= link_to login_path, class: "flex items-center gap-x-2 py-2 hover:bg-gray-300" do %>
							<i class="fa-solid fa-user-pen fa-xl"></i>
							<%= t('header.login') %>
						<% end %>
					</li>
					<li>
						<%= link_to list_of_support_path, class: "flex items-center gap-x-2 py-2 hover:bg-gray-300" do %>
							<i class="fa-solid fa-square-phone-flip fa-xl"></i>
							<%= t('header.support') %>
						<% end %>
					</li>
			</ul>
	</div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <ul class="text-red-700 bg-red-100">
      <% object.errors.each do |error| %>
        <li>・<%= error.full_message %></li>
    <% end %>
    </ul>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-base-200 rounded pb-10 mb-6 w-full">
    <div class="flex flex-col flex-grow">
      <div class="chat chat-start animate-shake-vertical" data-controller="view-chat">
        <div class="chat-image avatar" data-action="click->view-chat#preview">
        <%= button_tag(type: "button")  do %>
          <%= image_tag "characttor.png"%>
        <% end %>
        </div>
        <div class="chat-bubble chat-bubble-info mt-4 text-sm md:text-xl md:mt-10" data-view-chat-target="viewChat">
          僕の手帳を見るかい？
        </div>
      </div>
      <P class="ml-2 pt-2 text-xs lg:text-sm ml-4">(天才詐欺師)マドフくん</p>
    </div>
    <div class="mr-2 text-xs flex justify-end">
      <p>Copyright © 2024- 詐欺師の手帳</p>
    </div>
</footer>

app/views/shared/_header.html.erb
<header>
	<!--ヘッダー部分-->
	<div class="flex flex-row justify-between items-center bg-accent text-white w-full h-16 ">
		<div class="pl-4">
				<%= link_to t('header.title'),root_path %>
		</div>
			<div class="dropdown dropdown-end">
				<div tabindex="0" role="button" class="flex items-center py-2 px-4 text-sm btn m-1  mr-4 hover:bg-orange">
					<i class="fa-solid fa-bars fa-xl"></i>
				</div>
					<ul tabindex="0" class="dropdown-content menu bg-blue-100 text-slate-950 rounded-box z-[2] w-52 p-2 shadow">
						<li>
							<%= link_to profile_path, class: "flex items-center gap-x-2 py-2 hover:bg-gray-300" do %>
								<i class="fa-solid fa-id-card fa-xl"></i>
								<%= t('header.profile') %>
							<% end %>
						</li>
						<li>
							<%= link_to posts_path, class: "flex items-center gap-x-2 py-2 hover:bg-gray-300" do %>
								<i class="fa-solid fa-swatchbook fa-xl"></i>
								<%= t('header.posts') %>
							<% end %>
						</li>
						<li>
							<%= link_to logout_path, data: { turbo_method: :delete }, class: "flex items-center gap-x-2 py-2 hover:bg-gray-300" do %>
								<i class="fa-solid fa-right-from-bracket fa-xl"></i>
								<%= t('header.logout') %>
							<% end %>
						</li>
					</ul>
			</div>
	</div>

	<!--スマホサイド下部-->
		<div class="fixed inset-x-0 bottom-0 bg-accent text-white z-[2] w-full ">
			<div class="flex flex-row justify-between items-center py-4">
				<div class="grid"><!-- 左端の透明なスペース --></div>
				<% if current_page?(scams_path) %>
				<%= link_to scams_path do %>
					<i class="fa-solid fa-book-journal-whills text-orange fa-xl"></i>
				<% end %>
				<% else %>
					<%= link_to scams_path do %>
						<i class="fa-solid fa-book-journal-whills fa-xl"></i>
					<% end %>
				<% end %>
				<% if current_page?(new_post_path) %>
					<i class="fa-solid fa-pen-to-square text-orange fa-xl"></i>
				<% else %>
					<%= link_to new_post_path do %>
						<i class="fa-solid fa-pen-to-square fa-xl"></i>
					<% end %>
				<% end %>
				<% if current_page?(root_path) %>
					<i class="fa-solid fa-house-chimney text-orange fa-xl"></i>
				<% else %>
					<%= link_to root_path do %>
						<i class="fa-solid fa-house-chimney fa-xl"></i>
					<% end %>
				<% end %>
				<% if current_page?(line_notify_path) %>
					<i class="fa-solid fa-bell text-orange fa-xl"></i>
				<% else %>
					<%= link_to line_notify_path do %>
						<i class="fa-solid fa-bell fa-xl"></i>
					<% end %>
				<% end %>
				<% if current_page?(list_of_support_path) %>
					<i class="fa-solid fa-square-phone-flip text-orange fa-xl"></i>
				<% else %>
					<%= link_to list_of_support_path do%>
						<i class="fa-solid fa-square-phone-flip fa-xl"></i>
					<% end %>
				<% end %>
				<div class="grid"><!-- 右端の透明なスペース --></div>
			</div>
		</div>
</header>

app/views/shared/_search.html.erb
<%= search_form_for q, url: url, html: html, class: "flex items-center" do |f| %>
  <% if search_target == 'post' %>
    <div class="relative w-full" data-controller="autocomplete" data-autocomplete-min-length-value="2" data-autocomplete-url-value="/posts/autocomplete" role="combobox">
      <%= f.search_field :users_scam_name_cont, class: 'form-control flex-grow input input-bordered w-full', data: { autocomplete_target: 'input' }, placeholder: '詐欺名' %>
      <%= f.hidden_field :users_scam_name, data: { autocomplete_target: 'hidden' } %>
      <ul class="list-group text-xs md:text-base p-2 absolute w-full bg-cyan-100 z-10" data-autocomplete-target="results"></ul>
    </div>
  <% elsif search_target == 'scam' %>
    <div class="relative w-full" data-controller="autocomplete" data-autocomplete-min-length-value="2" data-autocomplete-url-value="/scams/autocomplete" role="combobox">
      <%= f.search_field :name_cont, class: 'form-control flex-grow input input-bordered w-full', data: { autocomplete_target: 'input' }, placeholder: '詐欺名' %>
      <%= f.hidden_field :name, data: { autocomplete_target: 'hidden' } %>
      <ul class="list-group text-xs md:text-base p-2 absolute w-full bg-cyan-100 z-10" data-autocomplete-target="results"></ul>
    </div>
  <% end %>
  <%= f.submit '検索', class: 'btn btn-success ml-2' %>
<% end %>