config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tops#index'
  get '/privacy_policy', to: 'tops#privacy_policy'
  get '/terms', to: 'tops#terms'
  get '/line_notify', to: 'tops#line_notify'
  get '/list_of_support', to: 'tops#list_of_support'

  resource :profile, only: %i[edit show update]

  resources :fraud_reports, only: %i[new create show]

  resources :scams, only: %i[index show] do
    collection do
      get 'autocomplete'
    end
  end

  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  resources :posts do
    resource :like, only: %i[create destroy]
    collection do
      get 'autocomplete'
    end
  end

  namespace :admin do
    root 'scams#index'
    resources :scams
    get 'login' => 'user_sessions#new', :as => :login
    post 'login' => 'user_sessions#create'
    delete 'logout' => 'user_sessions#destroy', :as => :logout
  end

  get 'images/ogp.png', to: 'images#ogp', as: 'images_ogp'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/controllers/admin/user_sessions_controller.rb
class Admin::UserSessionsController < Admin::BaseController
  skip_before_action :require_login, only: %i[new create]
  skip_before_action :check_admin, only: %i[new create]

  # 宣言しないとrailsはデフォルトではview/layouts/applicationにいく
  # ↓ログインページ用のレイアウトを用意するので宣言
  layout 'layouts/admin_login'

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to admin_root_path, notice: '管理画面にログインしました'
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to admin_login_path, notice: 'ログアウトしました', status: :see_other
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[create new]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path, notice: '僕の手帳を楽しんでくれ！'
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'またな！', status: :see_other
  end
end

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex flex-col items-center text-slate-950">
	<div class="card bg-gray-50 shadow-xl my-10 mx-4 w-4/5">
    <div class="card-body">
      <p class="flex justify-center font-mono text-orange text-xl md:text-2xl">ログインしてくれよな!</p>
    <%= form_with(url: login_path) do |f| %>
        <div class="flex flex-col m-2">
            <%= f.label :email, class: "input input-bordered flex items-center gap-2" do %>
							<i class="fa-solid fa-envelope"></i>
							<%= f.email_field :email,  class: "text-slate-950", placeholder: "メールアドレス" %>
						<% end %>
        </div>
        <div class="flex flex-col m-2">
            <%= f.label :password, class: "input input-bordered flex items-center gap-2" do %>
							<i class="fa-solid fa-key"></i>
							<%= f.password_field :password,  class: "text-slate-950", placeholder: "パスワード" %>
						<% end %>
        </div>
        <div class="flex flex-col m-2">
            <%= f.submit t('.login'), class: "btn rounded-full btn-warning text-base md:text-xl" %>
        </div>
    <% end %>
    </div>
  </div>
  <div class="flex flex-col">
    <%= link_to auth_at_provider_path(:provider => :line), method: :post, data: { turbo: false }, class: "w-full  flex items-center h-10 bg-[#06C755] text-white font-medium rounded shadow" do %>
      <%= image_tag 'btn_base.png', alt: 'LINE Icon', class: 'w-8 h-8 ml-4 mr-2' %>
      <span class="flex-1 text-xl text-center font-bold mr-10">LINEでログイン</span>
    <% end %>
    <div class="mt-10">
        <%= link_to "ユーザー登録", new_user_path, class: "btn rounded-full btn-success w-full text-xl" %>
    </div>
  </div>
</div>