config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tops#index'
  get '/privacy_policy', to: 'tops#privacy_policy'
  get '/terms', to: 'tops#terms'
  get '/line_notify', to: 'tops#line_notify'
  get '/list_of_support', to: 'tops#list_of_support'

  resource :profile, only: %i[edit show update]

  resources :fraud_reports, only: %i[new create show]

  resources :scams, only: %i[index show] do
    collection do
      get 'autocomplete'
    end
  end

  resources :users, only: %i[new create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  resources :posts do
    resource :like, only: %i[create destroy]
    collection do
      get 'autocomplete'
    end
  end

  namespace :admin do
    root 'scams#index'
    resources :scams
    get 'login' => 'user_sessions#new', :as => :login
    post 'login' => 'user_sessions#create'
    delete 'logout' => 'user_sessions#destroy', :as => :logout
  end

  get 'images/ogp.png', to: 'images#ogp', as: 'images_ogp'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/views/admin/shared/_header.html.erb
<header>
	<!--ヘッダー部分-->
	<div class="flex flex-row justify-between items-center bg-accent text-white w-full h-16 ">
		<div class="pl-4">
				<%= link_to t('header.title'),admin_root_path %>
		</div>
			<div class="dropdown dropdown-end">
				<div tabindex="0" role="button" class="flex items-center py-2 px-4 text-sm btn m-1  mr-4 hover:bg-orange">
					<i class="fa-solid fa-bars fa-xl"></i>
				</div>
					<ul tabindex="0" class="dropdown-content menu bg-blue-100 text-slate-950 rounded-box z-[2] w-52 p-2 shadow">
						<li>
							<%= link_to new_admin_scam_path, class: "flex items-center gap-x-2 py-2 hover:bg-gray-300" do %>
								<i class="fa-solid fa-swatchbook fa-xl"></i>
								<%= t('header.scams') %>
							<% end %>
						</li>
						<li>
							<%= link_to logout_path, data: { turbo_method: :delete }, class: "flex items-center gap-x-2 py-2 hover:bg-gray-300" do %>
								<i class="fa-solid fa-right-from-bracket fa-xl"></i>
								<%= t('header.logout') %>
							<% end %>
						</li>
					</ul>
			</div>
	</div>
</header>